version: '3'

volumes:
  static_data:
  media_data:

services:
  web:
    build: .
    tty: true
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/code/unitrade_dj
      - static_data:/code/unitrade_dj/staticfiles
      - media_data:/code/unitrade_dj/media
    ports:
      - "8000:8000"
