# Generated by Django 5.1 on 2025-01-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_product_price_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Название продукта"
            ),
        ),
    ]
