# Generated by Django 5.1 on 2025-02-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_product_external_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="about",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Название категории"
            ),
        ),
    ]
